"""initial_schema

Revision ID: c25bd1018dab
Revises: 
Create Date: 2026-03-02 19:58:05.339153+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c25bd1018dab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('key_hash', name=op.f('uq_api_keys_key_hash'))
    )
    op.create_index('idx_api_keys_active', 'api_keys', ['is_active'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('col_count', sa.Integer(), nullable=False),
    sa.Column('target_column', sa.String(length=255), nullable=False),
    sa.Column('time_column', sa.String(length=255), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('col_count >= 0', name=op.f('ck_datasets_positive_col_count')),
    sa.CheckConstraint('row_count >= 0', name=op.f('ck_datasets_positive_row_count')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets'))
    )
    op.create_index('idx_datasets_created_at', 'datasets', ['created_at'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued','running','completed','failed','cancelled')", name=op.f('ck_experiments_valid_experiment_status')),
    sa.CheckConstraint('progress_pct BETWEEN 0 AND 100', name=op.f('ck_experiments_valid_progress_pct')),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_experiments_dataset_id_datasets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments'))
    )
    op.create_index('idx_experiments_created_at', 'experiments', ['created_at'], unique=False)
    op.create_index('idx_experiments_dataset_id', 'experiments', ['dataset_id'], unique=False)
    op.create_index('idx_experiments_status', 'experiments', ['status'], unique=False)
    op.create_table('error_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('pattern_type', sa.String(length=20), nullable=False),
    sa.Column('subgroup_definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effect_size', sa.Float(), nullable=False),
    sa.Column('p_value', sa.Float(), nullable=False),
    sa.Column('adjusted_p_value', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.Column('mean_residual', sa.Float(), nullable=False),
    sa.Column('std_residual', sa.Float(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("pattern_type IN ('subgroup','cluster','interaction','temporal')", name=op.f('ck_error_patterns_valid_pattern_type')),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_error_patterns_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_patterns'))
    )
    op.create_index('idx_patterns_experiment_id', 'error_patterns', ['experiment_id'], unique=False)
    op.create_index('idx_patterns_type', 'error_patterns', ['pattern_type'], unique=False)
    op.create_table('experiment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_events_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_events'))
    )
    op.create_index('idx_events_created_at', 'experiment_events', ['created_at'], unique=False)
    op.create_index('idx_events_experiment_id', 'experiment_events', ['experiment_id'], unique=False)
    op.create_table('latent_variables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('construction_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_pattern_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('stability_score', sa.Float(), nullable=False),
    sa.Column('bootstrap_presence_rate', sa.Float(), nullable=False),
    sa.Column('model_improvement_pct', sa.Float(), nullable=True),
    sa.Column('confidence_interval_lower', sa.Float(), nullable=True),
    sa.Column('confidence_interval_upper', sa.Float(), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('candidate','validated','rejected')", name=op.f('ck_latent_variables_valid_lv_status')),
    sa.CheckConstraint('bootstrap_presence_rate BETWEEN 0.0 AND 1.0', name=op.f('ck_latent_variables_valid_bootstrap_rate')),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_latent_variables_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_latent_variables'))
    )
    op.create_index('idx_lv_experiment_id', 'latent_variables', ['experiment_id'], unique=False)
    op.create_index('idx_lv_status', 'latent_variables', ['status'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('fold_number', sa.Integer(), nullable=False),
    sa.Column('train_metric', sa.Float(), nullable=False),
    sa.Column('val_metric', sa.Float(), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('artifact_path', sa.String(length=512), nullable=True),
    sa.Column('hyperparams', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('feature_importances', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('training_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_models_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_models')),
    sa.UniqueConstraint('experiment_id', 'model_type', 'fold_number', name='uq_models_exp_type_fold')
    )
    op.create_index('idx_models_experiment_id', 'models', ['experiment_id'], unique=False)
    op.create_table('residuals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('model_type', sa.String(length=20), nullable=False),
    sa.Column('sample_index', sa.Integer(), nullable=False),
    sa.Column('fold_number', sa.Integer(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('residual_value', sa.Float(), nullable=False),
    sa.Column('abs_residual', sa.Float(), nullable=False),
    sa.Column('feature_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_residuals_experiment_id_experiments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_residuals'))
    )
    op.create_index('idx_residuals_experiment_fold', 'residuals', ['experiment_id', 'fold_number'], unique=False)
    op.create_index('idx_residuals_experiment_model', 'residuals', ['experiment_id', 'model_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_residuals_experiment_model', table_name='residuals')
    op.drop_index('idx_residuals_experiment_fold', table_name='residuals')
    op.drop_table('residuals')
    op.drop_index('idx_models_experiment_id', table_name='models')
    op.drop_table('models')
    op.drop_index('idx_lv_status', table_name='latent_variables')
    op.drop_index('idx_lv_experiment_id', table_name='latent_variables')
    op.drop_table('latent_variables')
    op.drop_index('idx_events_experiment_id', table_name='experiment_events')
    op.drop_index('idx_events_created_at', table_name='experiment_events')
    op.drop_table('experiment_events')
    op.drop_index('idx_patterns_type', table_name='error_patterns')
    op.drop_index('idx_patterns_experiment_id', table_name='error_patterns')
    op.drop_table('error_patterns')
    op.drop_index('idx_experiments_status', table_name='experiments')
    op.drop_index('idx_experiments_dataset_id', table_name='experiments')
    op.drop_index('idx_experiments_created_at', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('idx_datasets_created_at', table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('idx_api_keys_active', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
